version: 0.2

env:
  variables:
    BASE_TAG_NAME: base
    TAG_NAME: latest
    REPO_NAME: plugins-test-image  # see buildImageECRRepoName in cicd-stack.ts

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 028790571394.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - cd ubuntu/standard/7.0
      - docker build --tag $REPO_NAME:$TAG_NAME -f Dockerfile.funnel .
      - docker tag $REPO_NAME:$TAG_NAME 028790571394.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:$TAG_NAME
      - docker push 028790571394.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:$TAG_NAME